# Site settings
title: "Brigade - Event-driven scripting for Kubernetes."
email: "roflynnc@microsoft.com"
description: > # this means to ignore newlines until "baseurl:"
  Brigade is a tool for running scriptable automated tasks in the cloud. Brigade runs as part of a Kubernetes cluster.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://brigade.sh" # the base hostname & protocol for your site
twitter_username: helmpack
github_username:  deis

# Build settings
markdown: kramdown
include: ['.htaccess']
exclude: [docs, vendor, script, node_modules, Gruntfile.js, Gemfile, Gemfile.lock, package.json, s3_website.yml, gulpfile.js, README.md, Dockerfile, Makefile]
